import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import NextIntlProvider from './NextIntlProvider'
import { useMessages } from 'next-intl'
import { oswald } from '../ui/fonts'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function LocaleLayout({
  children, params }: {
    children: React.ReactNode,
    params: {locale: string}
  }) {

  const messages= useMessages();

  return (
    
    <html lang={params.locale} style={{ fontSize: '62.5%' }}>
      <link rel="icon" href="/favicon.ico" sizes="any" />
      <body className={oswald.className}>
        <NextIntlProvider
        locale={params.locale}
        messages={messages}
        now={new Date()}
        timeZone="Europe/Berlin"
        >
          
          {children}
        </NextIntlProvider>

      </body>
    </html>
  )
}
