import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import NextIntlProvider from './NextIntlProvider'
import { useMessages } from 'next-intl'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children, params }: {
    children: React.ReactNode,
    params: {locale: string}
  }) {
  // let messages;
  // try {
  //   messages = (await import(`../../../messages/${params.locale}.json`))
  //     .default;
  // } catch (error) {
  // }

  const messages= useMessages();

  return (
    <html lang={params.locale} style={{ fontSize: '62.5%' }}>
      <body className={inter.className}>
        <NextIntlProvider
        locale={params.locale}
        messages={messages}
        now={new Date()}
        timeZone="Europe/Berlin"
        >
          {children}
        </NextIntlProvider>
      </body>
    </html>
  )
}
